### ISSUE TITLE
index.js:1 Uncaught TypeError: Cannot read property 'objectOf' of undefined

### ISSUE THREAD

**Issue by wickr-pak** [gdowens/react-toggle-button#14]
Hi, I am getting this error after I npm installed the module. 

import ToggleButton from 'react-toggle-button'

index.js:1 Uncaught TypeError: Cannot read property 'objectOf' of undefined

These are my packages. 

"dependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "body-parser": "~1.17.1",
    "bootstrap": "^4.0.0-beta.2",
    "cookie-parser": "~1.4.3",
    "debug": "~2.6.3",
    "express": "~4.15.2",
    "hjs": "~0.0.6",
    "install": "^0.10.1",
    "jquery": "^3.2.1",
    "moment": "^2.19.1",
    "mongodb": "^2.2.33",
    "mongoose": "^4.13.0",
    "morgan": "~1.8.1",
    "npm": "^5.5.1",
    "popper.js": "^1.12.6",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-dropdown": "^1.3.2",
    "react-router-dom": "^4.2.2",
    "react-toggle-button": "^2.1.0",
    "serve-favicon": "~2.4.2",
    "superagent": "^3.8.0",
    "webpack": "^3.8.1"
  }

Help please.

**Comment by elad823** [comment]
Same issue for me. Any update?

**Comment by greygatch** [comment]
Same. @gdowens might know.

**Comment by gdowens** [comment]
Alright, just freshened it up. Try installing v2.2.0, the new package, which supports react 16.

**Comment by gdowens** [comment]
I'll take the reactions to indicate this issue has been resolved lol
