### ISSUE TITLE
Support for React 15?

### ISSUE THREAD

**Issue by stevesuh** [gdowens/react-toggle-button#2]
Any chance you can support React 15 to get rid of the warning?  Thanks for the great component!

`(program):44 Warning: Unknown props`inactiveLabel`,`activeLabel`,`thumbStyle`,`trackStyle`,`onToggle`,`colors`,`activeLabelStyle`,`activeLabelStyleHover`,`inactiveLabelStyle`,`inactiveLabelStyleHover`,`thumbStyleHover`,`animateThumbStyleHover`,`animateThumbStyleToggle`,`trackStyleHover`,`animateTrackStyleHover`,`animateTrackStyleToggle`,`thumbAnimateRange`,`internalSpringSetting`,`internalHoverSpringSetting`on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in input (created by Motion)
    in div (created by Motion)
    in Motion (created by Toggle)
`

**Comment by stevesuh** [comment]
I'm using react 15.3.0 and react-dom 15.3.0.

**Comment by gdowens** [comment]
I'll try and get around to it this weekend. Thanks for the heads up.

**Comment by stevesuh** [comment]
Thanks.  It's breaking some of my specs because the webpack compilation is complaining.

**Comment by renebrandel** [comment]
Is there any progress with this issue? My CI tool complains about this. That's why I sadly can't use it.

**Comment by renebrandel** [comment]
I created a pull request #4 that should fixed this. Can you review it?

**Comment by renebrandel** [comment]
Hey can you publish the changes of my pull request to npm?

**Comment by gdowens** [comment]
Sure, I'll do it when I get home. ~hour eta

**Comment by renebrandel** [comment]
Awesome ;-) Can you ping me when it's done? :)

**Comment by gdowens** [comment]
👍 2.1.0
